### ISSUE TITLE
is it possible to adjust the stream delay time

### ISSUE THREAD

**Issue by Mikeyzy** [vbence/stream-m#38]
i wander if it is possible to change the delay of the stream?
right now it is about 15-20 sec between my camera move and I see the movement on webpage. 
I don't mind to manually edit the code myself if you don't have time, as long as I know where to look for.

**Comment by vbence** [comment]
Hi, latency is added by every single element in your chain. First of all the encoder (are you using OBS?), depending on the preset the encoder will collect many frames before it starts to compress them, you can make sure a caprured frame is encoded immediately by choosing the `ultrafast` preset.

Because of the chunked encoding the lowest latency you can get is the keyframe interval. You can set this in your encoder. The lowest that still makes sense is around 2 seconds. You can set this by entering `keyint=60` to the Custom Encoder Settings box.
